// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtwnjs4HE0xiyaoF3RYqsgBxAkyoqy-rw',
    appId: '1:246422692459:web:3c1eb814a5bd8e6998072e',
    messagingSenderId: '246422692459',
    projectId: 'heavy-da21a',
    authDomain: 'heavy-da21a.firebaseapp.com',
    storageBucket: 'heavy-da21a.firebasestorage.app',
    measurementId: 'G-GD1TSVV3LM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCU7e6EySYE0wJD0gsnfwud_4qWFCQzrlM',
    appId: '1:246422692459:android:73f6facade20b96d98072e',
    messagingSenderId: '246422692459',
    projectId: 'heavy-da21a',
    storageBucket: 'heavy-da21a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkmjJQGVFTfUl02g_GftVyFB8EypPkofk',
    appId: '1:246422692459:ios:1a5d89642ec38d2098072e',
    messagingSenderId: '246422692459',
    projectId: 'heavy-da21a',
    storageBucket: 'heavy-da21a.firebasestorage.app',
    iosBundleId: 'com.example.tasks',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDkmjJQGVFTfUl02g_GftVyFB8EypPkofk',
    appId: '1:246422692459:ios:1a5d89642ec38d2098072e',
    messagingSenderId: '246422692459',
    projectId: 'heavy-da21a',
    storageBucket: 'heavy-da21a.firebasestorage.app',
    iosBundleId: 'com.example.tasks',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCtwnjs4HE0xiyaoF3RYqsgBxAkyoqy-rw',
    appId: '1:246422692459:web:9c3b5cee7789690498072e',
    messagingSenderId: '246422692459',
    projectId: 'heavy-da21a',
    authDomain: 'heavy-da21a.firebaseapp.com',
    storageBucket: 'heavy-da21a.firebasestorage.app',
    measurementId: 'G-1KJFVZ6VZD',
  );
}
